name: "Daily scrape"

on:
  schedule:
  - cron: "0 19 * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Execute scrape.py
      run: python scrape.py

    - name: Commit changes
      run: |
        git config --global user.email "antonio.feregrino+datasets@gmail.com"
        git config --global user.name "Antonio Feregrino"
        git add data/ scraped_urls.txt
        git diff --staged --quiet || git commit -m 'New blog posts'
        git push
    - name: Upload data to Kaggle
      env:
        KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        KAGGLE_USERNAME: ioexception
      run: python upload_kaggle.py
